apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-service
  namespace: banquito-core
  labels:
    app: party
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: party
  template:
    metadata:
      labels:
        app: party
    spec:
      serviceAccountName: party-secretmanager-ksa
      containers:
        - name: party-service
          image: us-central1-docker.pkg.dev/project-47695a8e-7cb2-4352-af2/banquito/party-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
            - name: grpc
              containerPort: 9093
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: DB_URL
              value: "jdbc:mysql://136.111.132.119:3306/partydb"
            - name: DB_USER
              value: root
            - name: IDENTITY_PLATFORM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: party-identity-platform-secrets
                  key: api-key
            - name: IDENTITY_PLATFORM_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: party-identity-platform-secrets
                  key: default-password
          envFrom:
            - configMapRef:
                name: banquito-config
            - secretRef:
                name: party-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 240
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 600
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 60
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi

