apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: party-identity-platform-secrets
  namespace: banquito-core
spec:
  serviceAccountName: party-secretmanager-ksa
  secretProviderClassName: party-identity-platform-secrets
  secretObject:
    type: Opaque
    data:
      - sourcePath: "identity-platform-api-key"
        targetKey: "api-key"
      - sourcePath: "identity-platform-clients-temp-password"
        targetKey: "default-password"
