apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: party-identity-platform-secrets
  namespace: banquito-core
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/project-47695a8e-7cb2-4352-af2/secrets/identity-platform-api-key/versions/latest"
        path: "identity-platform-api-key"
      - resourceName: "projects/project-47695a8e-7cb2-4352-af2/secrets/identity-platform-clients-temp-password/versions/latest"
        path: "identity-platform-clients-temp-password"
