server {
    listen 80;
    server_name personas.34.122.207.56.nip.io banquito-personas.duckdns.org;

    root /var/www/banquito/personas;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}

server {
    listen 80;
    server_name empresas.34.122.207.56.nip.io banquito-empresas.duckdns.org;

    root /var/www/banquito/empresas;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}

server {
    listen 80;
    server_name teller.34.122.207.56.nip.io banquito-teller.duckdns.org;

    root /var/www/banquito/teller;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}

server {
    listen 80;
    server_name operador.34.122.207.56.nip.io banquito-operador.duckdns.org;

    root /var/www/banquito/operador;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
