apiVersion: apps/v1
kind: Deployment
metadata:
  name: operador-frontend
  namespace: banquito-frontend
  labels:
    app: operador
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: operador
  template:
    metadata:
      labels:
        app: operador
    spec:
      containers:
        - name: operador-frontend
          image: us-central1-docker.pkg.dev/project-47695a8e-7cb2-4352-af2/banquito/operador-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: banquito-config
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi

