apiVersion: v1
kind: Service
metadata:
  name: clearinghouse-service
  namespace: banquito-switch
  labels:
    app: clearinghouse
spec:
  type: ClusterIP
  selector:
    app: clearinghouse
  ports:
    - name: http
      port: 8087
      targetPort: 8087
    - name: grpc
      port: 9094
      targetPort: 9094

