apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: banquito-switch
  labels:
    app: notification
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-service
          image: us-central1-docker.pkg.dev/project-47695a8e-7cb2-4352-af2/banquito/notification-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8089
            - name: grpc
              containerPort: 9092
          env:
            - name: SERVER_PORT
              value: "8089"
            - name: GRPC_PORT
              value: "9092"
            - name: GRPC_SERVER_PORT
              value: "9092"
          envFrom:
            - configMapRef:
                name: banquito-config
            - secretRef:
                name: mongo-services-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 240
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 600
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 30
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi

