apiVersion: v1
kind: Namespace
metadata:
  name: banquito-core
---
apiVersion: v1
kind: Namespace
metadata:
  name: banquito-switch
---
apiVersion: v1
kind: Namespace
metadata:
  name: banquito-pubsub
---
apiVersion: v1
kind: Namespace
metadata:
  name: banquito-gateway
