apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-core-pubsub-ksa
  namespace: banquito-core
  annotations:
    iam.gke.io/gcp-service-account: account-core-pubsub@project-47695a8e-7cb2-4352-af2.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-reception-pubsub-ksa
  namespace: banquito-switch
  annotations:
    iam.gke.io/gcp-service-account: file-reception-pubsub@project-47695a8e-7cb2-4352-af2.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-line-publisher-pubsub-ksa
  namespace: banquito-pubsub
  annotations:
    iam.gke.io/gcp-service-account: payment-line-publisher-pubsub@project-47695a8e-7cb2-4352-af2.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-line-subscriber-pubsub-ksa
  namespace: banquito-pubsub
  annotations:
    iam.gke.io/gcp-service-account: payment-line-subscriber-pubsub@project-47695a8e-7cb2-4352-af2.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clearinghouse-pubsub-ksa
  namespace: banquito-switch
  annotations:
    iam.gke.io/gcp-service-account: clearinghouse-pubsub@project-47695a8e-7cb2-4352-af2.iam.gserviceaccount.com
