apiVersion: v1
kind: Secret
metadata:
  name: banquito-secrets
  namespace: banquito-core
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://136.112.87.173:5432/banquito
  DB_USER: replace-with-db-user
  DB_PASS: replace-with-db-password
  POSTGRES_URL: jdbc:mysql://136.111.132.119:3306/tariffdb
  POSTGRES_USER: replace-with-mysql-user
  POSTGRES_PASSWORD: replace-with-mysql-password
  MONGO_URI: replace-with-mongodb-uri
  MONGODB_URI: replace-with-mongodb-uri
  SPRING_DATA_MONGODB_URI: replace-with-mongodb-uri
  SMTP_USER: replace-with-smtp-user
  SMTP_PASS: replace-with-smtp-password
---
apiVersion: v1
kind: Secret
metadata:
  name: banquito-secrets
  namespace: banquito-switch
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://136.112.87.173:5432/banquito
  DB_USER: replace-with-db-user
  DB_PASS: replace-with-db-password
  POSTGRES_URL: jdbc:mysql://136.111.132.119:3306/tariffdb
  POSTGRES_USER: replace-with-mysql-user
  POSTGRES_PASSWORD: replace-with-mysql-password
  MONGO_URI: replace-with-mongodb-uri
  MONGODB_URI: replace-with-mongodb-uri
  SPRING_DATA_MONGODB_URI: replace-with-mongodb-uri
  SMTP_USER: replace-with-smtp-user
  SMTP_PASS: replace-with-smtp-password
