apiVersion: v1
kind: Service
metadata:
  name: payment-line-publisher-service
  namespace: banquito-switch
  labels:
    app: payment-line-publisher
spec:
  type: ClusterIP
  selector:
    app: payment-line-publisher
  ports:
    - name: http
      port: 8092
      targetPort: 8092
