# ══════════════════════════════════════════════════════════════════════════════
# routing-service — Paul
# Copia esto a: src/main/resources/application.properties
# ══════════════════════════════════════════════════════════════════════════════

server.port=${SERVER_PORT:8085}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/routingdb}

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://banquito:banquito123@localhost:5672/banquito}

# Colas
input.queue=${INPUT_QUEUE:payment.lines.queue}
clearing.queue=${CLEARING_QUEUE:clearing.outbound.queue}

# URLs de otros servicios (para desarrollo local usa localhost, en Docker el docker-compose lo sobreescribe)
core.gateway.url=${CORE_GATEWAY_URL:http://localhost:8000/api/v2}
tariff.service.url=${TARIFF_SERVICE_URL:http://localhost:8086}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8089}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
