# ══════════════════════════════════════════════════════════════════════════════
# clearinghouse-service — Johan
# Copia esto a: src/main/resources/application.properties
# ══════════════════════════════════════════════════════════════════════════════

server.port=${SERVER_PORT:8087}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/clearingdb}

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://banquito:banquito123@localhost:5672/banquito}

# Colas
clearing.queue=${CLEARING_QUEUE:clearing.outbound.queue}

# URL Kong Core (para solicitar asientos contables a Bryan)
core.gateway.url=${CORE_GATEWAY_URL:http://localhost:8000/api/v2}

# Ruta donde se guardan los archivos TXT de compensación
output.path=${OUTPUT_PATH:/compensacion/outbound/}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
