
server.port=${SERVER_PORT:8088}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/routingdb}

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8089}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
