
server.port=${SERVER_PORT:8085}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/routingdb}

spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://banquito:banquito123@localhost:5672/banquito}

input.queue=${INPUT_QUEUE:payment.lines.queue}
clearing.queue=${CLEARING_QUEUE:clearing.outbound.queue}

core.gateway.url=${CORE_GATEWAY_URL:http://localhost:8000/api/v2}
tariff.service.url=${TARIFF_SERVICE_URL:http://localhost:8086}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8089}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
