
server.port=${SERVER_PORT:8087}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/clearingdb}

spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://banquito:banquito123@localhost:5672/banquito}

clearing.queue=${CLEARING_QUEUE:clearing.outbound.queue}

core.gateway.url=${CORE_GATEWAY_URL:http://localhost:8000/api/v2}

output.path=${OUTPUT_PATH:/compensacion/outbound/}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
