# ══════════════════════════════════════════════════════════════════════════════
# file-reception-service — Alan
# Copia esto a: src/main/resources/application.properties
# ══════════════════════════════════════════════════════════════════════════════

server.port=${SERVER_PORT:8084}

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/filedb}
spring.datasource.username=${DB_USER:banquito}
spring.datasource.password=${DB_PASS:banquito123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/filedb}

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://banquito:banquito123@localhost:5672/banquito}

# Colas
routing.queue=${ROUTING_QUEUE:payment.lines.queue}

# Horario de corte del Switch
cut.off.time=${CUT_OFF_TIME:18:00}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
