apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-payment-processor-service
  namespace: banquito-pubsub
  labels:
    app: internal-payment-processor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: internal-payment-processor
  template:
    metadata:
      labels:
        app: internal-payment-processor
    spec:
      containers:
        - name: internal-payment-processor-service
          image: us-central1-docker.pkg.dev/project-47695a8e-7cb2-4352-af2/banquito/internal-payment-processor-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8092
            - name: grpc
              containerPort: 9095
          env:
            - name: SERVER_PORT
              value: "8092"
            - name: PROCESSOR_GRPC_PORT
              value: "9095"
            - name: SPRING_APPLICATION_NAME
              value: banquito-internal-payment-processor-service
            - name: DB_URL
              value: "jdbc:mysql://136.111.132.119:3306/filedb"
            - name: DB_USER
              value: root
          envFrom:
            - configMapRef:
                name: banquito-config
            - secretRef:
                name: file-reception-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 360
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
