apiVersion: v1
kind: Service
metadata:
  name: internal-payment-processor-service
  namespace: banquito-pubsub
  labels:
    app: internal-payment-processor
spec:
  type: ClusterIP
  selector:
    app: internal-payment-processor
  ports:
    - name: http
      port: 8092
      targetPort: 8092
    - name: grpc
      port: 9095
      targetPort: 9095
