apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: banquito-switch
  labels:
    app: report
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report-service
          image: us-central1-docker.pkg.dev/project-47695a8e-7cb2-4352-af2/banquito/report-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8088
          env:
            - name: SERVER_PORT
              value: "8088"
          envFrom:
            - configMapRef:
                name: banquito-config
            - secretRef:
                name: mongo-services-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 180
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi

